package mirrg.xarpite

enum class OperatorMethod(val methodName: String) {
    PROPERTY("_._"),
    SET_PROPERTY("_._=_"),
    METHOD("_::_"),
    CALL("_(__)"),
    SET_CALL("_(__)=_"),
    BIND("_[__]"),
    TO_NUMBER("+_"),
    TO_BOOLEAN("?_"),
    TO_STRING("&_"),
    GET_LENGTH("$#_"),
    PLUS("_+_"),
    MINUS("_-_"),
    COMPARE("_<=>_"),
    CONTAINS("_@_"),
    MATCH("_=~_"),
    PLUS_ASSIGN("_+=_"),
    MINUS_ASSIGN("_-=_"),
    SUFFIX_INCREMENT("_++"),
    PREFIX_INCREMENT("++_"),
    SUFFIX_DECREMENT("_--"),
    PREFIX_DECREMENT("--_"),
}
