#!/usr/bin/env bash
if [ -z "$XARPITE_PROGRAM_NAME" ]; then
  XARPITE_PROGRAM_NAME="${0##*/}"
  export XARPITE_PROGRAM_NAME
fi
SCRIPT_DIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
CONFIG_FILE=$SCRIPT_DIR/default_engine
ENGINE="$XARPITE_ENGINE"
if [ -z "$ENGINE" ] && [ -f "$CONFIG_FILE" ]
then
  ENGINE="$(cat "$CONFIG_FILE")"
fi
ENGINE="${ENGINE:-native}"
if [ "$ENGINE" = "native" ]
then
  exec "$SCRIPT_DIR/bin/native/xarpite" "$@"
elif [ "$ENGINE" = "jvm" ]
then
  # JAVA_HOME is set by the system or user environment
  if [ -z "$JAVA_HOME" ]
  then
    exec java -jar "$SCRIPT_DIR/bin/jvm/xarpite-jvm.jar" "$@"
  else
    exec "$JAVA_HOME/bin/java" -jar "$SCRIPT_DIR/bin/jvm/xarpite-jvm.jar" "$@"
  fi
elif [ "$ENGINE" = "node" ]
then
  exec node "$SCRIPT_DIR/bin/node/xarpite-node.mjs" "$@"
else
  echo "Unsupported engine: $ENGINE" 1>&2
  exit 1
fi
